service: ${self:custom.tenant}-registration

plugins:
  - serverless-localstack
  - serverless-deployment-bucket

frameworkVersion: '2'

provider:
  name: aws
  runtime: java11
  stage: prod
  region: eu-central-1
  endpointType: REGIONAL
  apiGateway:
    shouldStartNameWithService: true
  memorySize: 3072
  timeout: 30
  deploymentBucket: ascheman.serverless.deployments.${self:provider.region}
  logRetentionInDays: 30
  environment:
    APP_DYNAMODB_TABLE: ${self:service}
    APP_EVENTS_DATA_BUCKET: ${self:custom.tenant}
    APP_TENANT_ID: ${self:custom.tenant}
    QUARKUS_PROFILE: ${self:custom.tenant}
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.APP_DYNAMODB_TABLE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.APP_DYNAMODB_TABLE}/index/*"
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.tenant}/*"
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendTemplatedEmail
        - ses:SendBulkTemplatedEmail
      Resource: ${self:custom.secrets.aws.sesIdentity}
    - Effect: Allow
      Action:
        - ses:CreateTemplate
        - ses:UpdateTemplate
      Resource: "*"

custom:
  tenant: ${opt:tenant, 'jugda'}
  secrets: ${ssm:/aws/reference/secretsmanager/${self:custom.tenant}-registration~true}
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost  # optional - LocalStack host to connect to
    edgePort: 4566  # optional - LocalStack edge port to connect to
    autostart: true  # optional - Start LocalStack in Docker on Serverless deploy
    lambda:
      # Enable this flag to improve performance
      mountCode: True
    docker:
      # Enable this flag to run "docker ..." commands as sudo
      sudo: False
  stages:
    local:

package:
  individually: true

functions:
  admin:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler
    events:
      - http:
          path: /admin/{proxy+}
          method: any
          authorizer:
            name: basicAuthorizer
            type: token
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 300
    package:
      artifact: target/function.zip
  public:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler
    environment:
      SLACK_OAUTH_ACCESS_TOKEN: ${self:custom.secrets.slack.access_token}
      SLACK_CHANNEL_GENERAL: ${self:custom.secrets.slack.channel_general}
    events:
      - http:
          path: /{proxy+}
          method: any
    package:
      artifact: target/function.zip
  basicAuthorizer:
    handler: js/basicAuthorizr.handler
    runtime: nodejs12.x
    memorySize: 128
    timeout: 3
    environment:
      REGISTRATION_ADMIN: ${self:custom.secrets.registration.admin}
      REGISTRATION_SECRET: ${self:custom.secrets.registration.secret}
    package:
      include:
        - js/basicAuthorizr.js
      exclude:
        - "*.*"
        - "*/**"

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: eventId
            AttributeType: S
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 2
        TableName: ${self:provider.environment.APP_DYNAMODB_TABLE}
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        SSESpecification:
          SSEEnabled: true
        GlobalSecondaryIndexes:
          -
            IndexName: event-email-index
            KeySchema:
              -
                AttributeName: eventId
                KeyType: HASH
              -
                AttributeName: email
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 2
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.WWW-Authenticate: "'Basic'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: ApiGatewayRestApi
        StatusCode: 401
